fitnessTracker/urls.py
from django.conf.urls import url

from . import views

app_name = "fitnessTracker"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'measurements', views.measurements, name="measurements")
]

fitness_tracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^fitnessTracker/', include('fitnessTracker.urls')),
    url(r'^admin/', admin.site.urls),
]

fitnessTracker/models.py
from django.db import models

# measurement track database
class Measurements(models.Model):
    timestamp = models.IntegerField() # unix timestamp
    weight = models.FloatField() # in kg
    waist  = models.FloatField() # in inches

# food database
class Foods(models.Model):
    name = models.CharField(max_length=100)
    alternateNames = models.CharField(max_length=200)
    #foodType = models.CharField()
    calories = models.FloatField()
    protein = models.FloatField()
    carbohydrates = models.FloatField()
    fat = models.FloatField()

# exercise database   
class Exercises(models.Model):
    name = models.CharField(max_length=100)
    #todo

# workout track database    
# TODO

# diet track database
# TODO

fitnessTracker/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

# main page
def index(request):
    return render(request, 'fitnessTracker/index.html')

# measurement page
def measurements(request):
    return render(request, 'fitnessTracker/measurements.html')

    

fitnessTracker/templates/fitnessTracker/index.html
<h1> Fitness Tracker </h1>

<ul>
<li><a href="{% url 'fitnessTracker:measurements' %}">Measurements (Coming Soon)</a></li>
<li><a href="">Workout (Coming Soon)</a></li>
<li><a href="">Diet (Coming Soon)</a></li>
<li><a href="">Progress (Coming Soon)</a></li>
</ul>

fitnessTracker/templates/fitnessTracker/measurements.html
<p> Previous measurement logs here </p>
<br/><br/>

<form method="post">
{% csrf_token %}
Weight <input type="input" name="weight"/>
Waist  <input type="input" name="waist"/>
<input type="submit" name="submit" value="Log"/>
</form>